### ISSUE TITLE
Change navigation

### ISSUE THREAD

**Issue by Tena99** [Tena99/quiz#20]
Currently it shows navigation buttons and next question button simultaneously. We need to hide the arrows above and switch the next page by the buttons below question. It's also recommended to change "previous/next question" to arrows. 

![Image](https://github.com/Tena99/quiz/assets/106435120/1889b4e4-6463-4106-b960-c2c90ae59256)

Besides we need to make the Start button work instead of arrows above.

![Image](https://github.com/Tena99/quiz/assets/106435120/0667f070-3a06-4283-a1d2-e2f173aa809a)

**Comment by D3NMOH** [comment]
Navigation functions linked inside components
